---
name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: "${{ matrix.os }} with Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "pypy3.10"]
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      - name: Install apt dependencies
        run: |
          set -ex
          sudo apt update
          sudo apt install -y ldap-utils slapd enchant-2 libldap2-dev libsasl2-dev apparmor-utils
        if: runner.os == 'Linux'
      - name: Disable AppArmor
        run: sudo aa-disable /usr/sbin/slapd
        if: runner.os == 'Linux'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Python dependencies"
        run: |
          set -xe
          python -V
          python -m pip install --upgrade pip setuptools build
      - name: "build python-ldap ${{ matrix.python-version }}"
        run: "python -m build"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: dist/*.whl
  release:
    name: "Release"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        # will download and upack all files from the default artifact named 'artifact'
        uses: actions/download-artifact@v3
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: latest
          files: |
            *.whl
